birdapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from graphene_django import GraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('enterdata/', include('enterdata.urls')),
    path('displaydata/', include('displaydata.urls')),
    path('', views.homePage),
    path('index/', views.homePage, name = 'homepage'),
]

urlpatterns += staticfiles_urlpatterns()

displaydata/urls.py
from django.urls import path
from . import views

app_name = 'displaydata'

urlpatterns = [
    path('', views.displayData, name = 'displaydata'),
    path('load_counties', views.load_counties, name ='ajax_load_counties'),
    path('create_linegraph/', views.create_linegraph, name= 'create_linegraph'),
    path('create_bargraph/', views.create_bargraph, name= 'create_bargraph'),

    path('export/', views.export, name= 'export'),

]

ecologysurvey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from graphene_django import GraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('enterdata/', include('enterdata.urls')),
    path('displaydata/', include('displaydata.urls')),
    path('', views.homePage),
    path('index/', views.homePage, name = 'homepage'),
 #   path('graphql/', GraphQLView.as_view(graphiql = True)),
]

urlpatterns += staticfiles_urlpatterns()

enterdata/urls.py
from django.urls import path
from . import views

app_name = 'enterdata'

urlpatterns = [
    path('', views.enterdata, name = 'enterdata'),
    path('submitted', views.submitted, name = 'submitted'),

    path('load_counties', views.load_counties, name ='ajax_load_counties')
]

enterdata/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE, PROTECT
from datetime import date

class Country(models.Model):
    name = models.CharField(max_length=50)
    class Meta: 
        ordering = ['name']

    def __str__(self):
        return self.name
    
class County(models.Model):
    name = models.CharField(primary_key=True, max_length=50)
    in_country = models.ForeignKey(Country, default=1, max_length=50, on_delete=CASCADE)
    #postcode = models.CharField(max_length=50, blank = True)

    class Meta: 
        ordering = ['name']

    def __str__(self):
        return self.name
    
class Species(models.Model):
    name = models.CharField(max_length=30)

    class Meta: 
        ordering = ['name']

    def __str__(self): 
        return self.name  #function to return the name of the instance of Species
        
class Sighting(models.Model):
    species = models.ForeignKey(Species, default=None, on_delete=PROTECT)
    date_seen = models.DateField(default=date.today)
    photo = models.ImageField(default ='default.png', blank = True)
        # def __str__ self.
    in_country = models.ForeignKey(Country, default = None, on_delete = PROTECT)
    in_county = models.ForeignKey(County, default = None, on_delete = CASCADE)
    #sound_file = models.FileField(upload_to=/'sounds/')
    #class Meta:
    # db_table='Audio_store'
    #maybe later add user 
    user = models.ForeignKey(User, default = None, on_delete = PROTECT)

    def __str__(self): 
        return self.species.name  #function to return the name of the instance of Species

enterdata/forms.py
from django import forms
from django.forms.widgets import DateInput
from . import models
import datetime
from django.core.validators import MaxValueValidator

class DateInput(forms.DateInput):
    input_type = 'date'

class EnterData(forms.ModelForm):
    date_seen = forms.DateField(widget = DateInput, validators = [MaxValueValidator(datetime.date.today)])

    class Meta:
        model = models.Sighting
        fields = ['species', 'date_seen', 'photo', 'in_country', 'in_county' ]

enterdata/views.py
from django import forms
from django.shortcuts import redirect, render
from .models import County, Species
from django.contrib.auth.decorators import login_required
from . import forms
from django.http.response import JsonResponse

@login_required(login_url="/accounts/login/") #this is so that the user can only add data if they are logged in, if not logged in, redirect to login page
def enterdata(request): 
    #species = Species.objects.all().order_by('name')
    
    if request.method == 'POST':
        form = forms.EnterData(request.POST, request.FILES) #to validate the data against the model form
        #to check if the user entered data properly: 
        if form.is_valid():
            #save the data to the database:
            instance_of_data_entry = form.save(commit=False) #created an instance of an article but don't commit to saving it yet
            instance_of_data_entry.user = request.user # to associate the person who collected the data with the logged in user   
            instance_of_data_entry.save()
            #redirect to somewhere
            return redirect('enterdata:submitted')
    else:
        form = forms.EnterData()
    return render(request, 'enterdata/enterdata.html', {'form':form}) 
    # add {'species':species} if want list of species on the page
        
#@login_required(login_url="/accounts/login/") #this is so that the user can only add data if they are logged in, if not logged in, redirect to login page
def submitted(request):
    return render(request, 'enterdata/submitted.html')

# AJAX
def load_counties(request):
    # print("we are here!")
    country_id = request.GET.get('country_id')
    # print(country_id) 
    counties = County.objects.filter(in_country_id=country_id).all()
    # print(counties)
    
    # print(JsonResponse(list(counties.values('in_country', 'name')), safe=False))
    return JsonResponse(list(counties.values('in_country', 'name')), safe=False)
   # return render(request, 'enterdata/county_dropdown_list_options.html', {'counties': counties})

enterdata/templates/enterdata/enterdata.html
{% extends 'base_layout.html' %}

{% block content %}
<!-- the loop below will probably not be needed in the end as we may end up not using names displayed  
 {% for species in species %}
    <h4><a href = "#"> {{ species.name }} </a> </h4>
 {% endfor %}
-->
<body>
 <h1 class = "welcome"> Hi {{ user.username }}! 
</h1>
<div> <h1> You can enter your data here. <h1>
</div> 
<div>
   Photo is optional.
</div>
   <h1>
   <form class = "site-form" id = "enterdataform" method ="post" data-counties-url = "{% url 'enterdata:ajax_load_counties' %}" enctype= "multipart/form-data">
      {% csrf_token %} <!--security measure token-->
     {% for field in form %}
         <div class = "fieldwrapper">
            {{field.errors}}
            {{field.label_tag }}
             <p class = "fieldsinform">
            {{field }}
            </p>
         </div>
         {% endfor %}
      <input type = "submit" id ="submit-button" name="submit-button" value= "Submit my data" href="submitted.html"/>
   </form> 
   </h1>

<h1 color = darkblue> 
<a href={% url 'displaydata:displaydata' %}>Show me some data! </a>
</h1>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
   $("#id_in_country").change(function () {
         const url = $("#enterdataform").attr("data-counties-url");  // get the url of the `load_counties` view
         const countryId = $(this).val();  // get the selected country ID from the HTML input
         console.log(url);
         console.log(countryId);
         $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /enterdata/ajax/load-counties/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {  
               console.log(data);
               var list = document.getElementById("id_in_county");
               console.log(list);
               list.innerHTML = ""; //clear all 
               let html_data = '<option value="">---------</option>';
               data.forEach(function (county) {
                  console.log(county);
                  html_data +=`<option value = "${county.name}"> ${county.name} </option>`
               });
               list.innerHTML = html_data; 
            }
        });
   });
</script>
{% endblock %}

enterdata/templates/enterdata/submitted.html
{% extends 'base_layout.html' %}

{% block content %}
 <h1 class = "submitted" action = "{% url 'enterdata:submitted' %}" method ="post" >
Thanks for submitting some data, {{ user.username }}!
</h1>
<h1>
<div class = "thank-you"> 
<a href="{% url 'displaydata:displaydata' %}"> Show me some data! </a>
</div>
<div class = "thank-you"> 
<a href="{% url 'enterdata:enterdata' %}"> Submit more data! </a>
</div>
</h1>
{% endblock %}

enterdata/templates/enterdata/type.html
{% extends 'base_layout.html' %}
{% block content %}
<body>
 <h1> Hi {{ user.username }}! <div> What type of species do you want to track? </div> </h1>
   <h1>
   <form class = "site-form" method = "post" action = "{% url 'enterdata:type' %}">
      {% csrf_token %} <!--security measure token-->
      <input type = "submit" name = "birddata" id="datachoice1" value = "birds"></input>
      <input type = "submit" name = "mushroomdata" id="datachoice2" value = "mushrooms"></input>
   </form> 
   </h1>
</body>
{%endblock%}