accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name = "signup"),
    path('login/', views.login_view, name ="login"),
    path('logout/', views.logout_view, name = "logout"),
]

birdapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from graphene_django import GraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('enterdata/', include('enterdata.urls')),
    path('displaydata/', include('displaydata.urls')),
    path('', views.homePage),
    path('index/', views.homePage, name = 'homepage'),
]

urlpatterns += staticfiles_urlpatterns()

displaydata/urls.py
from django.urls import path
from . import views

app_name = 'displaydata'

urlpatterns = [
    path('', views.displayData, name = 'displaydata'),
    path('load_counties', views.load_counties, name ='ajax_load_counties'),
    path('create_linegraph/', views.create_linegraph, name= 'create_linegraph'),
    path('create_bargraph/', views.create_bargraph, name= 'create_bargraph'),

    path('export/', views.export, name= 'export'),

]

ecologysurvey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from graphene_django import GraphQLView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('enterdata/', include('enterdata.urls')),
    path('displaydata/', include('displaydata.urls')),
    path('', views.homePage),
    path('index/', views.homePage, name = 'homepage'),
 #   path('graphql/', GraphQLView.as_view(graphiql = True)),
]

urlpatterns += staticfiles_urlpatterns()

enterdata/urls.py
from django.urls import path
from . import views

app_name = 'enterdata'

urlpatterns = [
    path('', views.enterdata, name = 'enterdata'),
    path('submitted', views.submitted, name = 'submitted'),

    path('load_counties', views.load_counties, name ='ajax_load_counties')
]

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> BirdApp </title>
    <link rel="stylesheet" href = "{% static 'kwakstyle.css' %}">
</head>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"> </script>
<script src="https://d3js.org/d3.v5.js"></script>
<body>
    <header>            
        <nav width = 100%>
        <div id = "logo" width = 100%>
            <img src = "{% static 'bird_blue.png' %}" style = "position: absolute; left: 0;" alt = "logo" width="110" height="110">
            {% if user.is_authenticated %}
                    <form class = "logout-link" action = "{% url 'accounts:logout' %}" method = "post">
                        {% csrf_token %} 
                        <button type = "submit"> Log out </button>
                    </form>
                    {% endif %}
        </div>
        <div width = 100%>
            {% if user.is_authenticated %}
                <li><a href = "{% url 'enterdata:enterdata' %}"> Add some data! </a></li>
                <li><a href = "{% url 'displaydata:displaydata' %}"> Show me some data! </a></li>
            {% else %}
                <li><a href = "{% url 'accounts:login' %}">Login</a></li>
                <li><a href = "{% url 'accounts:signup' %}">Sign up</a></li>
            {% endif %}
        </div>
        </nav>
    </header>
    <footer>
    </footer>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<header> 
{% if user.is_authenticated %}
<h1> Welcome to BirdApp, {{ user.username }}! <h1>
{% else %}
<h1> Welcome to BirdApp, fellow birder! <h1>
{%endif%}
</header>

<div class = "welcome-message">
    <h2>You can collect real bird data and get to see the data on some cool graphs! 
    <div> Additionally:
    </div>
        <li> you will be connected to a real database with data collected by thousands of people around the world </li> 
        <li> you will help research </li> 
        <li> you will expand your bird knowledge </li> 
    </h2>
</div>

 <div class="birdcontainer">
        <!--Sun-->
        <div id="sun"></div>

        <section id="bird-wrapper">
            <!--The bird-->
            <section id="bird">
                <div class="body">
                    <div class="crest">
                        <span class="crest-1"></span>
                        <span class="crest-2"></span>
                    </div>
                    <div class="head">
                        <span class="eye"></span>
                        <div class="mouth">
                            <span class="peak-top"></span>
                            <span class="peak-bottom"></span>
                            <span class="nouse"></span>
                            <div class="fish">
                                <div class="fin-top"></div>
                                <span class="body-left"></span>
                                <span class="body-right"></span>
                                <div class="fin-bottom"></div>
                            </div>
                        </div>
                        <div class="head-lines">
                            <span class="head-line-1"></span>
                            <span class="head-line-2"></span>
                        </div>
                    </div>
                    <div class="chest"></div>
                    <div class="feathers">
                        <span class="feather-1"></span>
                        <span class="feather-2"></span>
                        <span class="feather-3"></span>
                    </div>
                    <div class="wings">
                        <div class="wing-dots">
                            <div class="small dots-container">
                                <span class="small"></span>
                                <span class="small"></span>
                                <span class="small"></span>
                            </div>
                        <div class="big-dots-container">
                            <span class="big"></span>
                            <span class="big"></span>
                            <span class="big"></span>
                            <span class="big"></span>
                        </div>
                        </div>
                    </div>

                    <div class="legs"></div>
                    <div class="feet">
                        <div class="toes"></div>
                    </div>
                </div>
            </section>

            <!--Rock-->
            <div id="big-rock">
                <div class="rock-1"></div>
                <div class="rock-2"></div>
                <div class="rock-3"></div>

                <!--Rock grass-->
                <span class="rock-grass grass-1 left"></span>
                <span class="rock-grass grass-2 left"></span>
                <span class="rock-grass grass-3 left"></span>
                <span class="rock-grass grass-1 right"></span>
                <span class="rock-grass grass-2 right"></span>
                <span class="rock-grass grass-3 right"></span>
            </div>
        </section>
        <span class="grass"></span>
    </div>

{% endblock %}